export * from "./Home"
export * from "./About"
export * from "./MenuPerfil"
export * from "./RegistroCliente"
export * from "./RegistroAmigo"
export * from "./SubirFotos"
export * from "./SubirFotosA"
export * from "./Solicitud"
export * from "./EditarPerfil"
export * from "./Perfil"
export * from "./Services"
export * from "./ConoceMas"
export * from "./Soporte"
export * from "./PerfilUsuario"


{/*export * from "./Home"
export * from "./About"
export * from "./MenuPerfil"
export * from "./RegistroCliente"
export * from "./RegistroAmigo"
export * from "./Perfil"
export * from "./SubirFotos"
export * from "./Inicio"
export * from "./Solicitudes"
export * from "./Ayuda"
export * from "./Galeria"
export * from "./SeePerfil"
export * from "./Modificar" 
export * from "./ConoceMas"
export * from "./SeAmigo"
export * from "./Soporte"
export * from "./PerfilUsuario"
export * from "./EditarPerfil"*/ }
